#!/usr/bin/env bash

set -eu

if ! test -f /usr/lib/systemd/system/vboxservice.service; then
    exit 0
fi

print_blue "Setting up VirtualBox systemd service..."
$CHEZ_SUDO systemctl enable --now "vboxservice.service"
print_green "VirtualBox systemd service set up successfully."

if command -v VBoxClient-all >/dev/null; then
    print_blue "Ensuring VirtualBox user session services are started..."
    VBoxClient-all >/dev/null
    print_green "VirtualBox user session services started successfully."
fi
