#!/usr/bin/env bash

set -eu

print_blue "Installing Chaotic-AUR..."

if grep --quiet "chaotic-aur" /etc/pacman.conf; then
    print_green "Chaotic-AUR is already installed."
else
    CHAOTIC_KEY="3056513887B78AEB"
    CHAOTIC_CDN="https://cdn-mirror.chaotic.cx/chaotic-aur"

    $CHEZ_SUDO pacman-key --init

    $CHEZ_SUDO pacman-key --recv-key $CHAOTIC_KEY --keyserver keyserver.ubuntu.com
    $CHEZ_SUDO pacman-key --lsign-key $CHAOTIC_KEY

    $CHEZ_SUDO pacman -U --noconfirm $CHAOTIC_CDN/chaotic-{keyring,mirrorlist}.pkg.tar.zst

    cat <<'EOF' | $CHEZ_SUDO tee --append /etc/pacman.conf >/dev/null

[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

    $CHEZ_SUDO pacman -Sy --noconfirm
    print_green "Chaotic-AUR installed succesfully."
fi

print_blue "Installing Yay AUR helper..."
$CHEZ_SUDO pacman -S --needed --noconfirm yay
print_green "Yay installed successfully."

print_blue "Updating system to avoid partially updated dependencies..."
yay -Syu --noconfirm
print_green "System updated successfully."

print_blue "Installing pacman packages..."
# shellcheck disable=2086
yay -S --needed --noconfirm --assume-installed="vulkan-driver" $PACKAGES
print_green "Packages installed successfully."
