#!/usr/bin/env bash

set -eu

print_blue "Setting up GNOME extensions..."

if ! command -v gnome-extensions-cli >/dev/null; then
    print_blue "'gnome-extensions-cli' is not installed. Installing it..."

    if ! command -v uv >/dev/null; then
        print_red "'uv' is not installed. Aborting."
        exit 0
    fi

    uv tool install gnome-extensions-cli --with-requirements /dev/stdin <<<"pygobject"
    print_green "'gnome-extensions-cli' installed successfully."
fi

if gnome-extensions-cli --dbus &>/dev/null; then
    gext_args=("--dbus")
else
    gext_args=("--filesystem")
fi

extensions=(
    "AlphabeticalAppGrid@stuarthayhurst"          # Alphabetical App Grid
    "app-hider@lynith.dev"                        # App Hider
    "appindicatorsupport@rgcjonas.gmail.com"      # AppIndicator and KStatusNotifierItem Support
    "copyous@boerdereinar.dev"                    # Copyous
    "disable-menu-switching@selfmade.pl"          # Disable Menu Switching
    "middleclickclose@paolo.tranquilli.gmail.com" # Quick Close in Overview
    "panelScroll@sun.wxg@gmail.com"               # Panel Scroll
)

gnome-extensions-cli "${gext_args[@]}" install "${extensions[@]}"

if test "${gext_args[0]}" = "--filesystem"; then
    print_yellow "Re-log to apply changes."
fi

print_green "GNOME extensions set up successfully."
