#!/usr/bin/env bash

set -eu

print_blue "Setting up custom folder icons..."
FOLDER_ICONS=~/.local/share/icons/Morewaita/scalable/places

if ! command -v gio >/dev/null; then
    print_red "'gio' is not installed. Cannot change folder icons..."
    exit 0
fi

declare -A custom_icons=(
    [~/.config/GIMP]="folder-gimp"
    [~/.config/git]="folder-git"
    [~/.config/nvim]="folder-neovim"

    [~/.local]="folder-local"
    [~/.local/share/android]="folder-android"
    [~/.local/share/flatpak]="folder-flatpak"
    [~/.local/share/nvim]="folder-neovim"

    [~/Documents/Code]="folder-code"
    [~/Pictures/Screenshots]="folder-screenshot"
    [~/Vaults]="folder-private"
)

for folder in "${!custom_icons[@]}"; do
    icon="${custom_icons[$folder]}"

    test -d "$folder" || continue

    if ! test -f "$FOLDER_ICONS/$icon.svg"; then
        print_red "Icon '$FOLDER_ICONS/$icon.svg' not found."
        continue
    fi

    gio set "$folder" metadata::custom-icon-name "$icon"

done

print_green "Custom folder icons set up successfully."
