#!/usr/bin/env bash

set -eu

function dconf_append {
    key="$1" && new="$2"
    current=$(dconf read "$key")
    current=$(echo "${current:-"[]"}" | tr "'" '"')

    if ! command -v jq >/dev/null; then
        print_red "'jq' is not installed, cannot append '$new' to '$key'"
        return
    fi

    updated=$(jq --null-input --argjson current "$current" --arg new "$new" \
        '$current + [$new] | unique')

    dconf write "$key" "$(echo "$updated" | tr '"' "'")"
}

print_blue "Setting Dconf settings..."

# Input sources
test "$CHEZ_IS_PERSONAL" = "true" &&
    dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'us'), ('xkb', 'bg+phonetic')]"
dconf write /org/gnome/desktop/input-sources/per-window true

# Interface
dconf write /org/gnome/desktop/interface/gtk-enable-primary-paste false
dconf write /org/gnome/desktop/interface/gtk-theme "'adw-gtk3'"

# Mouse
dconf write /org/gnome/desktop/peripherals/mouse/accel-profile "'flat'"

# Keyboard
dconf write /org/gnome/desktop/peripherals/keyboard/numlock-state true

# WM keybindings
dconf write /org/gnome/desktop/wm/keybindings/show-desktop "['<Super>d']"
dconf write /org/gnome/desktop/wm/keybindings/switch-input-source "['<Alt>Shift_L']"
dconf write /org/gnome/desktop/wm/keybindings/switch-input-source-backward "['<Shift>Alt_L']"

# WM preferences
dconf write /org/gnome/desktop/wm/preferences/action-middle-click-titlebar "'minimize'"
dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier "'<Super>'"
dconf write /org/gnome/desktop/wm/preferences/resize-with-right-button true

# Mutter
dconf write /org/gnome/mutter/attach-modal-dialogs false

# Media keys
dconf write /org/gnome/settings-daemon/plugins/media-keys/help "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/home "['<Super>e']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/mic-mute "['Scroll_Lock']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-step 5

# Shell extensions
dconf write /org/gnome/shell/disable-extension-version-validation true
## App Hider
for app in \
  avahi-discover bssh btop bvnc nvim org.gnome.Settings org.gnome.Extensions \
  scrcpy scrcpy-console qv4l2 qvidcap yazi
do
    dconf_append /org/gnome/shell/extensions/app-hider/hidden-apps "${app}.desktop"
done
## Copyous
dconf write /org/gnome/shell/extensions/copyous/open-clipboard-dialog-shortcut "['<Super>v']"
dconf write /org/gnome/shell/extensions/copyous/sound "'hum'"

# Shell keybindings
dconf write /org/gnome/shell/keybindings/toggle-message-tray "['']"
dconf write /org/gnome/shell/keybindings/screenshot "['Print']"
dconf write /org/gnome/shell/keybindings/screenshot-window "['<Super>Print']"
dconf write /org/gnome/shell/keybindings/show-screenshot-ui "['<Shift><Super>s']"

print_green "Dconf configured successfully."
