#!/usr/bin/env bash

set -eu

print_blue "Setting Dconf settings..."

if ! command -v dconf >/dev/null; then
    print_yellow "Dconf not found. Skipping Dconf settings."
    exit 0
fi

# Input sources
if test "$CHEZ_IS_PERSONAL" = "true"; then
    dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'us'), ('xkb', 'bg+phonetic')]"
fi

dconf write /org/gnome/desktop/input-sources/per-window true

# Interface
dconf write /org/gnome/desktop/interface/gtk-enable-primary-paste false

# Mouse
dconf write /org/gnome/desktop/peripherals/mouse/accel-profile "'flat'"

# Keyboard
dconf write /org/gnome/desktop/peripherals/keyboard/numlock-state true

# WM keybindings
dconf write /org/gnome/desktop/wm/keybindings/screenshot "['Print']"
dconf write /org/gnome/desktop/wm/keybindings/screenshot-window "['<Super>Print']"
dconf write /org/gnome/desktop/wm/keybindings/show-desktop "['<Super>d']"
dconf write /org/gnome/desktop/wm/keybindings/show-screenshot-ui "['<Shift><Super>s']"
dconf write /org/gnome/desktop/wm/keybindings/switch-input-source "['<Alt>Shift_L']"
dconf write /org/gnome/desktop/wm/keybindings/switch-input-source-backward "['<Shift>Alt_L']"

# WM preferences
dconf write /org/gnome/desktop/wm/preferences/action-middle-click-titlebar "'minimize'"
dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier "'<Super>'"
dconf write /org/gnome/desktop/wm/preferences/resize-with-right-button true

# Mutter
dconf write /org/gnome/mutter/attach-modal-dialog false

# Media keys
dconf write /org/gnome/settings-daemon/plugins/media-keys/help "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/home "['<Super>e']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/mic-mute "['Scroll_Lock']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-step 5

print_green "Dconf configured successfully."
