#!/bin/sh

set -eu # exit on [e]rror and [u]nset variables

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
NORMAL='\033[0m'

cd

if ! chezmoi="$(command -v chezmoi)"; then
    host="get.chezmoi.io"
    chezmoi="${HOME}/.local/bin/chezmoi"

    printf "${BLUE}%b\n${NORMAL}" "Downloading chezmoi to '${chezmoi}' ..."

    if command -v curl >/dev/null; then
        chezmoi_script="$(curl -fsSL $host)"
    elif command -v wget >/dev/null; then
        chezmoi_script="$(wget -qO- $host)"
    elif command -v openssl >/dev/null; then
        chezmoi_script="$(printf 'GET / HTTP/1.0\nHost:%s\n\n' $host | openssl s_client -quiet $host:443 2>/dev/null)"
    else
        printf "${RED}%b\n${NORMAL}" "To install chezmoi, you must have curl or wget installed."
        exit 1
    fi

    BINDIR=~/.local/bin sh -c "${chezmoi_script}"
fi

set -- init --apply iliqiliev --depth 1

printf "${GREEN}%b\n${NORMAL}" "Running 'chezmoi $*' ..."
exec "$chezmoi" "$@"
