{{- $repo := "ryanoasis/nerd-fonts" }}

{{- if not .installGui }}
{{-   abortEmpty }}
{{- end -}}

[adwaita_mono]
type = "archive"
url = {{ gitHubLatestReleaseAssetURL $repo "AdwaitaMono.tar.xz" | quote }}
exact = false
refreshPeriod = "672h"
include = ["*.ttf"]

[ubuntu_mono]
type = "archive"
url = {{ gitHubLatestReleaseAssetURL $repo "UbuntuMono.tar.xz" | quote }}
exact = false
refreshPeriod = "672h"
include = ["*.ttf"]
