#!/bin/sh

set -eu # exit on [e]rror and [u]nset variables

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
NORMAL='\033[0m'

cd

if ! chezmoi="$(command -v chezmoi)"; then
    chezmoi_url="https://get.chezmoi.io/lb"
    chezmoi="${HOME}/.local/bin/chezmoi"

    printf "%b\n" "${BLUE}Installing chezmoi to '${chezmoi}'${NORMAL}"

    if command -v curl >/dev/null; then
        chezmoi_install_script="$(curl -fsSL $chezmoi_url)"
    elif command -v wget >/dev/null; then
        chezmoi_install_script="$(wget -qO- $chezmoi_url)"
    else
        printf "%b\n" "${RED}To install chezmoi, you must have curl or wget installed.${NORMAL}" >&2
        exit 1
    fi

    sh -c "${chezmoi_install_script}"
    unset chezmoi_install_script chezmoi_url
fi

set -- init --apply iliqiliev

printf "%b\n" "${GREEN}Running 'chezmoi $*'${NORMAL}" >&2
exec "$chezmoi" "$@"
