#!/bin/sh

set -eu # exit on [e]rror and [u]nset variables

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
NORMAL='\033[0m'

cd

if ! chezmoi="$(command -v chezmoi)"; then
    chezmoi_url="https://get.chezmoi.io/lb"
    chezmoi="${HOME}/.local/bin/chezmoi"

    printf "${BLUE}%b\n${NORMAL}" "Installing chezmoi to '${chezmoi}'"

    if command -v curl >/dev/null; then
        chezmoi_install_script="$(curl -fsSL $chezmoi_url)"
    elif command -v wget >/dev/null; then
        chezmoi_install_script="$(wget -qO- $chezmoi_url)"
    else
        printf "${RED}%b\n${NORMAL}" "To install chezmoi, you must have curl or wget installed." >&2
        exit 1
    fi

    sh -c "${chezmoi_install_script}"
    unset chezmoi_install_script chezmoi_url
fi

set -- init --apply iliqiliev

printf "${GREEN}%b\n${NORMAL}" "Running 'chezmoi $*' ..."
exec "$chezmoi" "$@"
