[project]
name = "dotfiles"
version = "1.0.0"
requires-python = ">=3.9"

dependencies = [
  "requests",
  "rich",
  "vdf",
  "winrt-Windows.ApplicationModel; sys_platform == 'win32'",
  "winrt-Windows.Foundation.Collections; sys_platform == 'win32'",
  "winrt-Windows.Management.Deployment; sys_platform == 'win32'",
]

[build-system]
requires = ["uv_build<0.12"]
build-backend = "uv_build"

[tool.basedpyright]
reportUnusedCallResult = false

[tool.ruff]
extension = { "py.tmpl" = "python" }
lint.ignore = [
  "PLW1510",  # Allow `subprocess.run` without explicit `check` argument.
]

[tool.uv]
python-preference = "system"
build-backend.module-root = ""
build-backend.module-name = ["helpers"]
environments = [
  "sys_platform == 'android' and implementation_name == 'cpython'",
  "sys_platform == 'linux' and implementation_name == 'cpython'",
  "sys_platform == 'win32' and implementation_name == 'cpython'",
]
