[project]
name = "dotfiles"
version = "1.0.0"
requires-python = ">=3.12"

dependencies = [
  "kodistubs",
  "requests",
  "rich",
  "vdf",
  "winrt-Windows.ApplicationModel; sys_platform == 'win32'",
  "winrt-Windows.Foundation.Collections; sys_platform == 'win32'",
  "winrt-Windows.Management.Deployment; sys_platform == 'win32'",
]

[build-system]
requires = ["uv_build<0.13"]
build-backend = "uv_build"

[tool.basedpyright]
reportUnusedCallResult = false

[tool.ruff]
extension = { "py.tmpl" = "python" }
src = [".", "home/private_dot_local/share/kodi/addons/service.chezmoi.bootstrap"]
lint.ignore = [
  "EXE001",  # Allow shebangs in non-executable files.
  "PLW1510",  # Allow `subprocess.run` without explicit `check` argument.
]

[tool.ty]
environment.python-platform = "all"
environment.root = ["home/private_dot_local/share/kodi/addons/service.chezmoi.bootstrap"]

[tool.uv]
python-preference = "system"
build-backend.module-root = ""
build-backend.module-name = ["helpers"]
environments = [
  "sys_platform == 'android' and implementation_name == 'cpython'",
  "sys_platform == 'linux' and implementation_name == 'cpython'",
  "sys_platform == 'win32' and implementation_name == 'cpython'",
]
