#!/usr/bin/bash

export PACKAGES="yadm fish micro git-delta eza bat zoxide fastfetch"
export RED="\033[31m"
export GREEN="\033[32m"
export RESET="\033[0m"

if {
    command -v pacman &&
    command -v sudo &&
    groups | grep --quiet --word-regexp --extended-regexp "sudo|wheel"
} > /dev/null 2>&1; then
    sudo pacman -S --needed --noconfirm $PACKAGES   
else
    echo "Please install the following packages manually:"
    echo -e "${GREEN}${PACKAGES}${RESET}"
    echo "Exit the shell afterwards so that the bootstrap can continue."
    PS1="  (install):\$ " bash --norc --noprofile -i
fi

~/.cache/yadm sparse-checkout set --no-cone \
"/*" \
"!README.md" \
"!install" \
"!.gitattributes"

if command -v fish > /dev/null 2>&1; then
    fish --command "
        yes | fish_config theme save 'Old School'
        curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher
        if type --quiet fisher
            fisher update
        end
    "
fi

if gsettings list-schemas | grep --quiet org.gnome > /dev/null 2>&1; then
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt>Shift_L']"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift>Alt_L']"
    gsettings set org.gnome.desktop.peripherals.mouse accel-profile "flat"
else
    echo -e "${RED}Could not detect GNOME, skipping its settings.${RESET}"
fi
