#!/bin/sh

if { command -v pacman && command -v sudo; } > /dev/null 2>&1; then
    sudo pacman -S --needed --noconfirm \
    yadm micro fish git-delta
fi

if command -v fish > /dev/null 2>&1; then
    fish --command "yes | fish_config theme save 'Old School'"
fi

if command -v gsettings > /dev/null 2>&1; then
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt>Shift_L']"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift>Alt_L']"
fi
