#!/usr/bin/env bash

set -eu

print_blue "Syncing apt database..."
$CHEZ_SUDO apt update -y
print_green "Apt database synced successfully."

AVAILABLE_PACKAGES=$(
    comm -12 \
        <(apt-cache pkgnames | sort) \
        <(echo "$PACKAGES" | tr " " "\n")
)

print_blue "Installing apt packages..."
# shellcheck disable=2086
$CHEZ_SUDO apt install -y $AVAILABLE_PACKAGES
print_green "Packages installed successfully."
