#!/usr/bin/fish

set HOME "$XDG_DATA_HOME"/android

if ps -C scrcpy >/dev/null
    pkill scrcpy
       
else
    timeout 3 adb connect 192.168.1.8:5555
    scrcpy --no-video --audio-buffer=250
    
end
