#!/usr/bin/bash -e

# IDK
DEBUG=0

# File location
VEGA_PATH="/sys/class/drm/card1/device"

# Wait 5s to avoid problems
# sleep 5

# Power limit at 205W
upp --pp-file="$VEGA_PATH"/pp_table set --write \
      /PowerTuneTable/SocketPowerLimit=205 \
      /PowerTuneTable/BatteryPowerLimit=205 \
      /PowerTuneTable/SmallPowerLimit=205 \

# Sets gpu performance level control to manual
# Then changes the power profile mode
echo performance > "$VEGA_PATH"/power_dpm_state
echo manual > "$VEGA_PATH"/power_dpm_force_performance_level
echo 1 > "$VEGA_PATH"/pp_power_profile_mode

      # The other power profile modes are:
      #   1 = 3D_FULL_SCREEN
      #   4 = VR
      #   5 = COMPUTE

#GPU Clock and Voltage
echo "s 0 852 800" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 1 991 817" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 2 1084 832" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 3 1138 852" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 4 1200 920" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 5 1420 985" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 6 1536 1030" > "$VEGA_PATH/pp_od_clk_voltage"
echo "s 7 1536 1030" > "$VEGA_PATH/pp_od_clk_voltage"

# Memory Clock and Voltage
echo "m 0 167 800" > "$VEGA_PATH/pp_od_clk_voltage"
echo "m 1 500 800" > "$VEGA_PATH/pp_od_clk_voltage"
echo "m 2 850 900" > "$VEGA_PATH/pp_od_clk_voltage"
echo "m 3 1040 980" > "$VEGA_PATH/pp_od_clk_voltage"

# Commit changes
echo "c" > "$VEGA_PATH/pp_od_clk_voltage"
