#!/usr/bin/env bash

set -eu

# shellcheck source=helpers/env.sh
source ~/.local/share/chezmoi/helpers/env.sh

if command -v uv >/dev/null; then
    exit 0
fi

print_blue "'uv' not found in PATH, installing it manually..."

UV_URL="https://astral.sh/uv/install.sh"

if command -v curl >/dev/null; then
    uv_script="$(curl -LSfs $UV_URL)"
elif command -v wget >/dev/null; then
    uv_script="$(wget -qO- $UV_URL)"
else
    print_red "Neither curl nor wget are installed. Aborting."
    exit 1
fi

export UV_NO_MODIFY_PATH=1
export UV_PRINT_QUIET=1

bash -c "${uv_script}"

print_green "'uv' installed successfully."
