arch = {
  packages = [
    "bat",
    "btop",
    "chezmoi",
    "curl",
    "eza",
    "fastfetch",
    "fd",
    "fish",
    "fzf",
    "git",
    "git-delta",
    "neovim",
    "ripgrep",
    "shellcheck",
    "tealdeer",
    "yazi",
    "zoxide",
  ]
}
