#!/usr/bin/env bash

# This is an associative array, a feature introduced in Bash 4.
# Syntax:
# [Executable name]=[Package name]

declare -A PACKAGES=(
    [bat]=bat
    [btop]=btop
    [delta]=git-delta
    [eza]=eza
    [fastfetch]=fastfetch
    [fish]=fish
    [fzf]=fzf
    [micro]=micro
    [rg]=ripgrep
    [shellcheck]=shellcheck
    [tldr]=tealdeer
    [yadm]=yadm
    [yazi]=yazi
    [zoxide]=zoxide
)

for package in "${!PACKAGES[@]}"; do
    if command -v "$package" &> /dev/null; then
        if [ "$package" = "yadm" ] && (( $(type -aP "yadm" | wc --lines) < 2 )); then
            continue
        fi

        unset "PACKAGES['$package']"
    fi
done


if (( ${#PACKAGES[@]} == 0 )); then

PS1=$(cat << EOF
$GREEN Good job! Type exit to continue.
$GREEN (done):\$ $NORMAL
EOF
)

else

PS1=$(cat << EOF
$YELLOW Install these packages:$GREEN ${PACKAGES[*]}
$YELLOW Hint: you can use the APPS variable to reference them all.
$YELLOW (install):\$ $NORMAL
EOF
)

fi

FILE_00=${BASH_SOURCE[0]}

export PS1
export APPS=${PACKAGES[*]}
export PROMPT_COMMAND="source $FILE_00"
