#!/usr/bin/env bash

# This is an associative array, a feature introduced in Bash 4.
# Syntax:
# [Executable name]=[Package name]

declare -A PACKAGES=(
    [bat]=bat
    [btop]=btop
    [delta]=git-delta
    [eza]=eza
    [fastfetch]=fastfetch
    [fish]=fish
    [fzf]=fzf
    [micro]=micro
    [rg]=ripgrep
    [tldr]=tealdeer
    [yadm]=yadm
    [yazi]=yazi
    [zoxide]=zoxide
)

for package in ${!PACKAGES[@]}; do
    if command -v $package &> /dev/null; then
        unset PACKAGES[${package}]
    fi
done
