#!/usr/bin/env bash

# This is an associative array, a feature introduced in Bash 4.
# Syntax:
# [Executable name]=[Package name]

declare -A PACKAGES=(
    [bat]=bat
    [btop]=btop
    [delta]=git-delta
    [eza]=eza
    [fastfetch]=fastfetch
    [fish]=fish
    [fzf]=fzf
    [micro]=micro
    [rg]=ripgrep
    [tldr]=tealdeer
    [yadm]=yadm
    [yazi]=yazi
    [zoxide]=zoxide
)

for package in "${!PACKAGES[@]}"; do
    if command -v "$package" &> /dev/null; then
        if [ "$package" = "yadm" ] && (( $(type -aP "yadm" | wc --lines) < 2 )); then
            continue
        fi

        unset "PACKAGES['$package']"
    fi
done

if (( ${#PACKAGES[@]} == 0 )); then
    export PS1="$GREEN  (done):\$ $NORMAL"
else
    export PS1="$YELLOW (install): ${PACKAGES[*]}\n :\$ $NORMAL"
fi

THIS_FILE=${BASH_SOURCE[0]}
export PROMPT_COMMAND="source $THIS_FILE"
