#!/usr/bin/env bash

if ! yadm diff --quiet; then
    echo -e $YELLOW
    yadm stash push --message="Local files before yadm bootstrap."
    echo -e $GREEN
    echo "Use 'yadm stash show --patch' to view them."
    echo "Then either 'yadm stash pop' to restore them or 'yadm stash drop' to delete them forever."
    echo -e $NORMAL
fi

cd

yadm sparse-checkout set --no-cone \
"/*" \
"!README.md" \
"!install" \
"!.gitattributes"
