#!/usr/bin/env bash

export YADM=~/.cache/yadm

if ! $YADM diff --quiet; then
    echo -e $YELLOW
    $YADM stash push --message="Local files before yadm bootstrap."
    echo -e $GREEN
    echo "Use 'yadm stash show --patch' to view them."
    echo "Then either 'yadm stash pop' to restore them or 'yadm stash drop' to delete them forever."
    echo -e $NORMAL
fi

$YADM sparse-checkout set --no-cone \
"/*" \
"!README.md" \
"!install" \
"!.gitattributes"
