#!/usr/bin/env bash

if ! yadm diff --quiet; then
    echo -ne $YELLOW
    yadm stash push --message="Local files before yadm bootstrap."
    echo -ne $GREEN
    echo "Use 'yadm stash show --patch' to view them."
    echo "Then either 'yadm stash pop' to restore them or 'yadm stash drop' to delete them forever."
    echo -ne $NORMAL
fi

cd

yadm sparse-checkout set --no-cone \
"/*" \
"!README.md" \
"!install" \
"!.gitattributes"

echo -ne $GREEN
echo "Sparse checkout applied successfully."
echo -ne $NORMAL
