#!/usr/bin/env bash

source $(dirname $0)/00-packages

echo "Please install the following packages:"
echo -ne $GREEN
echo ${PACKAGES[@]}
echo -ne $NORMAL
echo "Exit the shell afterwards so that the bootstrap can continue."

PS1="$GREEN  (install):\$ $NORMAL" bash --norc --noprofile -i
