#!/usr/bin/env bash

cd

SPARSE_DIRS=$(yadm list | grep -vE "^.github/*|^.gitattributes\$" | xargs -n 1 dirname | sort -u)

yadm sparse-checkout set $SPARSE_DIRS

echo -ne $GREEN
echo "Sparse checkout applied successfully."
echo -ne $NORMAL
