#!/usr/bin/env bash

PACKAGES_FILE=$(dirname $(readlink -e ${BASH_SOURCE[0]}))/00-packages
source $PACKAGES_FILE

if (( ${#PACKAGES[@]} == 0 )); then
    exit 0
fi

echo "Please install the listed packages:"
echo "Exit the shell afterwards so that the bootstrap can continue."

PROMPT_COMMAND="source $PACKAGES_FILE" bash --norc --noprofile -i || true
