#!/usr/bin/env bash

source $(dirname $0)/00-packages

if (( ${#PACKAGES[@]} == 0 )); then
    exit 0
fi

echo "Please install the listed packages:"
echo "Exit the shell afterwards so that the bootstrap can continue."

trap "source $(dirname $0)/00-packages" DEBUG

bash --norc --noprofile -i || true
