#!/usr/bin/env bash

source $(dirname ${BASH_SOURCE[0]})/00-packages

if (( ${#PACKAGES[@]} == 0 )); then
    echo -ne $GREEN
    echo "All packages installed."
    echo -ne $NORMAL
    exit 0
fi

echo -ne $RED
echo "Please install the still missing packages manually!"
echo "Exit the shell afterwards so that the bootstrap can continue."
echo -ne $NORMAL

bash --norc --noprofile -i || true
