#!/usr/bin/env bash

set -e

if command -v fish &> /dev/null; then
    exit 0
fi

if [ "$(uname --kernel-name)" != "Linux" ]; then
    exit 0
fi

FISH_BIN_PATH=~/.local/bin
FISH_BASE_URL="https://github.com/fish-shell/fish-shell/releases/download"

case $(uname --machine) in
  x86_64) FISH_STATIC_URL="$FISH_BASE_URL/4.0.2/fish-static-amd64-4.0.2.tar.xz";;
  aarch64) FISH_STATIC_URL="$FISH_BASE_URL/4.0.2/fish-static-aarch64-4.0.2.tar.xz";;
  *) exit 1;;
esac

echo -ne "$YELLOW"
echo "Fish shell not found. Installing static build to '$FISH_BIN_PATH' manually."

echo "Downloading..."
curl --location $FISH_STATIC_URL --progress-bar | tar --extract --xz --directory=$FISH_BIN_PATH

echo "yes" | $FISH_BIN_PATH/fish --install --no-execute
echo -ne "$GREEN"
echo "Fish shell installed successfully."
echo -ne "$NORMAL"
