#!/usr/bin/env bash

FISH_STATIC_URL="https://github.com/fish-shell/fish-shell/releases/download/4.0.2/fish-static-amd64-4.0.2.tar.xz"
FISH_BIN_PATH=~/.local/bin

if ! command -v fish &> /dev/null; then
    exit 0
fi

echo -ne $YELLOW
echo "Fish shell still not found. Installing static x86_64 build to '$FISH_BIN_PATH' manually."
echo -ne $NORMAL

curl --location $FISH_STATIC_URL | tar --extract --xz --directory=$FISH_BIN_PATH && {
    $FISH_BIN_PATH/fish --command "fish --install"

    echo -ne $GREEN
    echo "Fish shell installed successfully."
    echo -ne $NORMAL
}


