#!/usr/bin/env bash

FISH_STATIC_URL="https://github.com/fish-shell/fish-shell/releases/download/4.0.2/fish-static-amd64-4.0.2.tar.xz"
FISH_BIN_PATH=~/.local/bin

source $(dirname $0)/00-packages

if [[ ! -v PACKAGES[fish] ]]; then
    exit 0
fi

echo -ne $YELLOW
echo "Fish shell still not found. Installing static x86_64 build to '$FISH_BIN_PATH' manually."
echo -ne $NORMAL

curl --location $FISH_STATIC_URL | tar --extract --xz --directory=$FISH_BIN_PATH && {
    echo -ne $GREEN
    echo "Fish shell installed successfully."
    echo -ne $NORMAL
}


