#!/usr/bin/env sh

set -eu

. "$CHEZMOI_SOURCE_DIR/.chezmoi/chezmoi.bash"

if test "$CHEZ_SUDO" = "false"; then
    exit 0
fi

print_blue "Installing apk packages..."
# shellcheck disable=2086
$CHEZ_SUDO apk add $PACKAGES
print_green "Packages installed successfully."
