#!/usr/bin/env sh

set -eu

printf "${BLUE}%b\n${NORMAL}" "Installing apk packages..."
# shellcheck disable=2086
$CHEZ_SUDO apk add $PACKAGES
printf "${GREEN}%b\n${NORMAL}" "Packages installed successfully."
