#!/usr/bin/env bash

set -e

for entry in "$(dirname "${BASH_SOURCE[0]}")"/registry_entries/*.reg; do
    echo -n "Registry entry '$(basename "$entry")': "
    reg.exe import "$entry"
done

echo -e "\n${GREEN}Imported registry entries succesfully.${NORMAL}"

{
    taskkill.exe -f -im explorer.exe && powershell.exe "start explorer.exe"
} >/dev/null
echo "Explorer restarted to apply changes."
