[bootstrap.packages]
"apk:build-base" = "latest"  # `tree-sitter` needs `cc`.
"apt:gcc" = "latest"  # `tree-sitter` needs `cc`.
"pacman:gcc" = "latest"  # `tree-sitter` needs `cc`.

[env]
HOME = { default = "$USERPROFILE" }
# XDG User Directories:
XDG_CACHE_HOME = "$HOME/.cache"
XDG_CONFIG_HOME = "$HOME/.config"
XDG_DATA_HOME = "$HOME/.local/share"
XDG_STATE_HOME = "$HOME/.local/state"

[tool_alias]
bashls = "npm:bash-language-server"
brush = "cargo:brush-shell"
fish-lsp = "npm:fish-lsp"
tclint = "pipx:tclint"
fish = "aqua:fish-shell/fish-shell"  # Unused.

[tools]
cargo-binstall = "latest"
lua-language-server = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tombi = "latest"
topgrade = "latest"
tree-sitter = "latest"
ty = "latest"
usage = "latest"

[tools.bashls]
version = "latest"

[tools.brush]
depends = "cargo-binstall"
os = ["windows"]
version = "latest"

[tools.fish-lsp]
os = ["linux"]
version = "latest"

[tools.tclint]
uvx_args = "--quiet"
version = "latest"

[settings]
cargo.binstall_only = true
cargo.binstall_quickinstall = true
minimum_release_age_excludes = ["ruff", "ty", "uv"]
