[bootstrap.packages]
# `tree-sitter` needs a C compiler.
"apk:gcc" = "latest"
"apt:gcc" = "latest"
"dnf:gcc" = "latest"
"pacman:gcc" = "latest"

[env]
HOME = { default = "$USERPROFILE" }
# XDG User Directories:
XDG_CACHE_HOME = "$HOME/.cache"
XDG_CONFIG_HOME = "$HOME/.config"
XDG_DATA_HOME = "$HOME/.local/share"
XDG_STATE_HOME = "$HOME/.local/state"

[tool_alias]
bashls = "npm:bash-language-server"
fish-lsp = "npm:fish-lsp"
sqruff = "aqua:quarylabs/sqruff"
tclint = "pipx:tclint"
ts_query_ls = "github:ribru17/ts_query_ls"

[tools]
starship = "latest"
topgrade = "latest"
usage = "latest"
zoxide = "latest"

[tools.bashls]
depends = "node"
version = "latest"
lazy = true
lazy_bins = ["bash-language-server"]

[tools.fish-lsp]
depends = "node"
os = ["linux"]
version = "latest"
lazy = true
lazy_bins = ["fish-lsp"]

[tools.lua-language-server]
version = "latest"
lazy = true

[tools.node]
version = "latest"
lazy = true

[tools.ruff]
version = "latest"
lazy = true

[tools.shellcheck]
version = "latest"
lazy = true

[tools.shfmt]
version = "latest"
lazy = true

[tools.sqruff]
version = "latest"
lazy = true
lazy_bins = ["sqruff"]

[tools.stylua]
version = "latest"
lazy = true

[tools.tclint]
uvx_args = "--quiet"
version = "latest"
lazy = true
lazy_bins = ["tclfmt", "tclint", "tclsp"]

[tools.tombi]
version = "latest"
lazy = true

[tools.tree-sitter]
version = "latest"
lazy = true

[tools.ts_query_ls]
version = "latest"
lazy = true
lazy_bins = ["ts_query_ls"]

[tools.ty]
version = "latest"
lazy = true

[settings]
minimum_release_age_excludes = ["ruff", "ty", "uv"]
node.compile = false
