[bootstrap.packages]
"apt:libatomic1" = "latest"  # Required by `node`.

[env]
# $HOME is not set on Windows.
HOME = { default = "$USERPROFILE" }
# XDG User Directories:
XDG_BIN_HOME = "$HOME/.local/bin"
XDG_CACHE_HOME = "$HOME/.cache"
XDG_CONFIG_HOME = "$HOME/.config"
XDG_DATA_HOME = "$HOME/.local/share"
XDG_STATE_HOME = "$HOME/.local/state"
# Environment Variables:
NPM_CONFIG_USERCONFIG = "$XDG_CONFIG_HOME/npm/npmrc"  # For `node`.

[tool_alias]
# Used Aliases:
basedpyright = "npm:basedpyright"
bashls = "npm:bash-language-server"
brush = "cargo:brush-shell"
fish-lsp = "npm:fish-lsp"
powershell-es = "github:PowerShell/PowerShellEditorServices"
tclint = "pipx:tclint"
# Unused Aliases:
fish = "aqua:fish-shell/fish-shell"

[tools]
# Core Tools:
cargo-binstall = "latest"
lua-language-server = "latest"
node = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tombi = "latest"
topgrade = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
# Aliased Tools:
basedpyright = "latest"
bashls = "latest"
brush = { version = "latest", os = "windows" }
fish-lsp = "latest"
powershell-es = "latest"
tclint = "latest"

[settings.node]
compile = false

[settings.python]
compile = false

[settings.cargo]
binstall_only = true
binstall_quickinstall = true
