# {% set env_values = [] %}
# {% if "/etc/alpine-release" is exists %}
#   {% set env_values = [...env_values, "alpine"] %}
# {% elif env.TERMUX_VERSION is defined %}
#   {% set env_values = [...env_values, "termux"] %}
# {% endif %}

env = [
  # {% for env_value in env_values %}
  "{{ env_value }}",
  # {% endfor %}
]
