; {{ $zenPath := "" }}
; {{ if eq .os "linux" }}
; {{   $zenPath = "/opt/zen-browser-bin" }}
; {{ else if eq .os "windows" }}
; {{   $zenPath = joinPath .chezmoi.homeDir "scoop" "apps" "zen-browser" "current" }}
; {{ else }}
; {{   abortEmpty }}
; {{ end }}
;
; {{ $releaseId := mozillaInstallHash $zenPath }}
; {{ $profilePath := joinPath .chezmoi.homeDir ".config" "zen" "profile" }}

[Profile0]
Name={{ .distro }}-{{ .chezmoi.hostname }}
IsRelative=0
Path={{ $profilePath }}
Default=1

[General]
StartWithLastProfile=1
Version=2

[Install{{ $releaseId }}]
Default={{ $profilePath }}
Locked=1
