#!/usr/bin/env bash

set -eu

if test "$CHEZ_DISTRO" != "arch"; then
    exit 0
fi

# shellcheck source=helpers/helpers.sh
source "$CHEZMOI_WORKING_TREE"/helpers/helpers.sh

if test "$CHEZ_SUDO" = "false"; then
    exit 0
fi

if ! test -d /run/systemd/system; then
    exit 0
fi

print_blue "Setting up Sched_ext ..."

if systemctl is-active --quiet scx_loader; then
    print_green "Sched_ext is already configured."
    exit 0
fi

$CHEZ_SUDO pacman -S --needed --noconfirm scx-tools

$CHEZ_SUDO dd status=none of=/etc/scx_loader.toml <<EOF
default_sched = "scx_lavd"
default_mode = "Gaming"

[scheds.scx_lavd]
auto_mode = []
gaming_mode = ["--performance"]
lowlatency_mode = ["--performance"]
powersave_mode = ["--powersave"]
server_mode = []
EOF

$CHEZ_SUDO systemctl enable --now scx_loader
print_green "Sched_ext installed and enabled successfully."
