#!/usr/bin/env bash

set -eu

if test "$CHEZ_DISTRO" != "android"; then
    exit 0
fi

# shellcheck source=helpers/env.sh
source "$CHEZMOI_WORKING_TREE"/helpers/env.sh

if ! test -L "$HOME/storage/shared"; then
    print_blue "Setting up Termux storage ..."

    if ! command -v termux-setup-storage >/dev/null; then
        print_red "'termux-setup-storage' command not found."
        exit 0
    fi

    termux-setup-storage
    print_green "Termux storage setup successfully."
fi

print_blue "Copying files to Internal Storage ..."

TERMUX_SRC="$CHEZMOI_WORKING_TREE"/termux

while read -r file_src; do

    file_dst="$HOME/${file_src#"$TERMUX_SRC"/}"

    if cmp --quiet "$file_src" "$file_dst"; then
        continue
    fi

    cp "$file_src" "$file_dst"
    file_copied=true

    echo -e "~${file_src#"$HOME"} -> ~${file_dst#"$HOME"}\n"

done < <(find "$TERMUX_SRC" -type f)

if test -n "${file_copied-}"; then
    echo -en "$ANSI_CURSOR_PREVIOUS_LINE"
fi

print_green "Termux files copied successfully."
