#!/usr/bin/env bash

set -eu

if ! test -L "$HOME/storage/shared"; then
    print_blue "Setting up Termux storage..."

    if ! command -v termux-setup-storage >/dev/null; then
        print_red "'termux-setup-storage' command not found."
        exit 0
    fi

    termux-setup-storage
    print_green "Termux storage setup successfully."
fi

print_blue "Copying files to Internal Storage..."

TERMUX_SRC="$CHEZMOI_SOURCE_DIR/.chezmoi/termux"
TERMUX_DST="$HOME"

find "$TERMUX_SRC" -type f | while IFS= read -r file_src; do
    relative_part="${file_src#"$TERMUX_SRC"/}"
    file_dst="$TERMUX_DST/$relative_part"

    cp "$file_src" "$file_dst" --verbose
done

print_green "Termux files copied successfully."
