#!/usr/bin/env bash

set -eu

# shellcheck source=.chezmoi/env.sh
source ~/.local/share/chezmoi/.chezmoi/env.sh

if ! test -L "$HOME/storage/shared"; then
    print_blue "Setting up Termux storage..."

    if ! command -v termux-setup-storage >/dev/null; then
        print_red "'termux-setup-storage' command not found."
        exit 0
    fi

    termux-setup-storage
    print_green "Termux storage setup successfully."
fi

print_blue "Copying files to Internal Storage..."

TERMUX_SRC="$CHEZMOI_SOURCE_DIR/.chezmoi/termux"
TERMUX_DST="$HOME"

while read -r file_src; do
    relative_part="${file_src#"$TERMUX_SRC"/}"
    file_dst="$TERMUX_DST/$relative_part"

    if cmp --quiet "$file_src" "$file_dst"; then
        continue
    fi

    cp "$file_src" "$file_dst"
    file_copied=true

    echo "$file_src"
    echo "was copied to"
    echo "$file_dst"
    echo
done < <(find "$TERMUX_SRC" -type f)

if test -n "$file_copied"; then
    echo -e "$ANSI_CURSOR_PREVIOUS_LINE"
fi

print_green "Termux files copied successfully."
