#!/usr/bin/env bash

set -eu

print_blue "Setting up Termux storage..."

if ! command -v termux-setup-storage >/dev/null; then
    print_red "'termux-setup-storage' command not found."
    exit 0
fi

termux-setup-storage

print_green "Termux storage setup successfully."
