#!/usr/bin/env bash

set -eu

print_blue "Syncing apt database..."
apt update -y
print_green "Apt database synced successfully."

print_blue "Upgrading termux packages..."
yes | apt full-upgrade
print_green "Packages upgraded successfully."
