#!/usr/bin/env ash

set -eu

# shellcheck source=helpers/env.sh
source ~/.local/share/chezmoi/helpers/env.sh

if ! rc-status &>/dev/null; then
    exit 0 # OpenRC is not running
fi

if ! test -f /etc/init.d/virtualbox-guest-additions; then
    exit 0
fi

print_blue "Setting up VirtualBox guest additions..."
$CHEZ_SUDO rc-service virtualbox-guest-additions start
$CHEZ_SUDO rc-update add virtualbox-guest-additions boot
print_green "VirtualBox guest additions set up successfully."

if test -f /etc/init.d/virtualbox-drm-client; then
    print_blue "Setting up additional graphics service..."
    $CHEZ_SUDO rc-service virtualbox-drm-client start
    $CHEZ_SUDO rc-update add virtualbox-drm-client default
    print_green "Additional graphics service set up successfully."
fi
