# Do not check sourced files.
# shellcheck source=/dev/null

# ignoredups, ignorespace, erasedups
export HISTCONTROL=ignoreboth:erasedups

# Add ~/.local/bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# Source ble.sh
if test -r ~/.local/share/blesh/ble.sh; then
    source -- ~/.local/share/blesh/ble.sh
fi

# Aliases
alias ll="ls -l"
alias la="ls -la"
command -v eza >/dev/null && alias ls="eza" && alias tree="eza -T"
command -v bat >/dev/null && alias cat="bat"
command -v fdfind >/dev/null && alias fd="fdfind"

# Source starship.rs
source -- ~/.config/bash/starship.bash
