#!/usr/bin/env bash

set -eu

# shellcheck source=helpers/env.sh
source ~/.local/share/chezmoi/helpers/env.sh

print_blue "Setting up custom folder icons ..."
FOLDER_ICONS=~/.local/share/icons/Morewaita/scalable/places

if ! command -v gio >/dev/null; then
    print_red "'gio' is not installed. Cannot change folder icons ..."
    exit 0
fi

declare -A custom_icons=(
    [~/.cache]="folder-temp"

    [~/.config]="folder-user"
    [~/.config/containers]="folder-podman"
    [~/.config/copyous@boerdereinar.dev]="folder-extensions"
    [~/.config/dconf]="folder-gnome"
    [~/.config/fish]="folder-shell"
    [~/.config/gh]="folder-github"
    [~/.config/GIMP]="folder-gimp"
    [~/.config/git]="folder-git"
    [~/.config/kitty]="folder-shell"
    [~/.config/MangoHud]="folder-games"
    [~/.config/nautilus]="folder-gnome"
    [~/.config/nvim]="folder-neovim"
    [~/.config/powershell]="folder-shell"
    [~/.config/yay]="folder-archlinux"
    [~/.config/zed]="folder-code"
    [~/.config/zen]="folder-globe"

    [~/.local]="folder-local"
    [~/.local/share/android]="folder-android"
    [~/.local/share/cargo]="folder-rust"
    [~/.local/share/containers]="folder-podman"
    [~/.local/share/fish]="folder-shell"
    [~/.local/share/flatpak]="folder-flatpak"
    [~/.local/share/gnome-shell]="folder-gnome"
    [~/.local/share/gnome-shell/extensions]="folder-extensions"
    [~/.local/share/keyrings]="folder-private"
    [~/.local/share/nautilus]="folder-gnome"
    [~/.local/share/nvim]="folder-neovim"
    [~/.local/share/powershell]="folder-shell"
    [~/.local/share/uv]="folder-python"
    [~/.local/share/zed]="folder-code"

    [~/.ssh]="folder-shell"

    [~/.var]="folder-flatpak"

    [~/Documents/Code]="folder-code"
    [~/Pictures/Camera]="folder-camera"
    [~/Pictures/GIMP]="folder-gimp"
    [~/Pictures/Screenshots]="folder-screenshot"
    [~/Projects]="folder-projects"
    [~/Vaults]="folder-private"
    [~/Videos/Screencasts]="folder-screencast"
)

for folder in "${!custom_icons[@]}"; do
    icon="${custom_icons[$folder]}"

    test -d "$folder" || continue

    if ! test -f "$FOLDER_ICONS/$icon.svg"; then
        print_red "Icon '$FOLDER_ICONS/$icon.svg' not found."
        continue
    fi

    gio set "$folder" metadata::custom-icon-name "$icon"

done

print_green "Custom folder icons set up successfully."
