name: PSScriptAnalayzer

on:
  push:
    paths:
      - "**.ps1"
  workflow_dispatch:

jobs:
  psscriptanalyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer `
            -EnableExit `
            -ExcludeRule `
              PSAvoidUsingInvokeExpression, `
              PSAvoidUsingPositionalParameters, `
              PSAvoidUsingWriteHost, `
              PSUseShouldProcessForStateChangingFunctions `
            -Path ./ `
            -Recurse `
            | Format-List
