name: Find bugs in powershell scripts. 

on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

jobs:
  psscriptanalyzer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@main
        with:
          path: .\
          recurse: true
